# Generated by Django 4.1 on 2022-09-04 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NTEECategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='NTEECode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.nteecategory')),
            ],
        ),
        migrations.CreateModel(
            name='Nonprofit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('altname', models.CharField(max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=5)),
                ('zip', models.CharField(max_length=12)),
                ('county', models.CharField(max_length=20)),
                ('has_website', models.BooleanField(null=True)),
                ('has_facebook', models.BooleanField(null=True)),
                ('has_contact', models.BooleanField(null=True)),
                ('needs_volunteers', models.BooleanField(null=True)),
                ('needs_review', models.BooleanField(null=True)),
                ('review_comment', models.TextField(null=True)),
                ('website_url', models.CharField(max_length=200, null=True)),
                ('facebook_url', models.CharField(max_length=200, null=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('ntee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.nteecode')),
            ],
        ),
    ]
