# Generated by Django 4.0.7 on 2022-09-03 13:39

from django.db import migrations
import csv

def import_ntee_codes(apps, schema_editor):
    NTEECategory = apps.get_model('main', 'NTEECategory')
    NTEECode = apps.get_model('main', 'NTEECode')
    with open('main/data/nteecodes.csv') as csvfile:
        reader = csv.DictReader(csvfile,
            ['code', 'name', 'category', 'description'])
        for row in reader:
            print(row['code'], row['name'])
            nc = NTEECategory.objects.get(
                category=row['category'])
            code = NTEECode(
                code=row['code'],
                name=row['name'],
                description=row['description'],
                category=nc)
            code.save()

def remove_ntee_codes(apps, schema_editor):
    NTEECode = apps.get_model('main', 'NTEECode')
    NTEECode.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_nteecategories'),
    ]

    operations = [
        migrations.RunPython(import_ntee_codes, remove_ntee_codes)
    ]
