# Generated by Django 4.0.7 on 2022-09-03 13:48


from django.db import migrations
import csv

def build_address(number, street):
    return f'{number} {street}'

def valid_county(county):
    valid_counties = [ 
        'Champaign County',
        'Clark County',
        'Darke County',
        'Greene County',
        'Logan County',
        'Miami County',
        'Montgomery County',
        'Preble County',
        'Shelby County',
        'Mercer County',
        'Auglaize County',
    ]
    if county in valid_counties:
        return True
    return False

def import_nonprofits(apps, schema_editor):
    NTEECode = apps.get_model('main', 'NTEECode')
    Nonprofit = apps.get_model('main', 'Nonprofit')
    with open('main/data/nonprofits.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        # 'EIN', 'NAME', 'ICO', 'STREET', 'CITY',
        # 'STATE', 'ZIP', 'GROUP', 'SUBSECTION',
        # 'AFFILIATION', 'CLASSIFICATION',
        # 'RULING', 'DEDUCTIBILITY', 'FOUNDATION',
        # 'ACTIVITY', 'ORGANIZATION', 'STATUS',
        # 'TAX_PERIOD', 'ASSET_CD', 'INCOME_CD',
        # 'FILING_REQ_CD', 'PF_FILING_REQ_CD',
        # 'ACCT_PD', 'ASSET_AMT', 'INCOME_AMT',
        # 'REVENUE_AMT', 'NTEE_CD', 'SORT_NAME',
        # 'Latitude', 'Longitude', 'Accuracy Score',
        # 'Accuracy Type', 'Number', 'Street',
        # 'City', 'State', 'County', 'Zip',
        # 'Country', 'Source']
        for row in reader:
            if not valid_county(row['County']):
                print('skipping', row['County'])
                continue

            nc = None
            if row['NTEE_CD'] is not None and row['NTEE_CD'] is not '':
                print('code', row['NTEE_CD'])
                nc = NTEECode.objects.get(
                    code=row['NTEE_CD'][:3])
            nonprofit = Nonprofit(
                ein=row['EIN'],
                name=row['NAME'],
                ntee=nc,
                altname=row['SORT_NAME'],
                latitude=row['Latitude'],
                longitude=row['Longitude'],
                address=build_address(row['Number'], row['Street']),
                city=row['City'],
                state=row['State'],
                zip=row['Zip'],
                county=row['County'],
                has_website=None,
                has_facebook=None,
                has_contact=None,
                needs_volunteers=None,
                needs_review=None,
                review_comment=None)
            nonprofit.save()

def remove_nonprofits(apps, schema_editor):
    Nonprofit = apps.get_model('main', 'Nonprofit')
    Nonprofit.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_nteecodes'),
    ]

    operations = [
        migrations.RunPython(import_nonprofits, remove_nonprofits)
    ]
