# Generated by Django 4.1.1 on 2022-09-05 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_nonprofits'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nonprofit',
            name='has_facebook',
        ),
        migrations.RemoveField(
            model_name='nonprofit',
            name='has_website',
        ),
        migrations.AddField(
            model_name='nonprofit',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
