# Generated by Django 4.1.1 on 2022-09-20 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_nonprofit_has_facebook_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RawNonprofit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('ico', models.CharField(max_length=200, null=True)),
                ('street', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=200, null=True)),
                ('state', models.CharField(max_length=3, null=True)),
                ('zip', models.CharField(max_length=15, null=True)),
                ('group', models.IntegerField(null=True)),
                ('subsection', models.IntegerField(null=True)),
                ('affiliation', models.IntegerField(null=True)),
                ('classification', models.IntegerField(null=True)),
                ('ruling', models.IntegerField(null=True)),
                ('deductibility', models.IntegerField(null=True)),
                ('foundation', models.IntegerField(null=True)),
                ('activity', models.IntegerField(null=True)),
                ('organization', models.IntegerField(null=True)),
                ('status', models.IntegerField(null=True)),
                ('tax_period', models.IntegerField(null=True)),
                ('asset_cd', models.IntegerField(null=True)),
                ('income_cd', models.IntegerField(null=True)),
                ('filing_req_cd', models.IntegerField(null=True)),
                ('pf_filing_req_cd', models.IntegerField(null=True)),
                ('acct_pd', models.IntegerField(null=True)),
                ('asset_amt', models.IntegerField(null=True)),
                ('income_amt', models.IntegerField(null=True)),
                ('revenue_amt', models.IntegerField(null=True, blank=True)),
                ('ntee_cd', models.CharField(max_length=15, null=True)),
                ('sort_name', models.CharField(max_length=200, null=True)),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=8, null=True)),
                ('geo_accuracy_score', models.DecimalField(decimal_places=2, max_digits=4, null=True)),
                ('geo_accuracy_type', models.CharField(max_length=25)),
                ('geo_number', models.CharField(max_length=20, null=True)),
                ('geo_street', models.CharField(max_length=100)),
                ('geo_city', models.CharField(max_length=40)),
                ('geo_state', models.CharField(max_length=3)),
                ('geo_county', models.CharField(max_length=25)),
                ('geo_zip', models.IntegerField()),
                ('geo_country', models.CharField(max_length=3)),
                ('geo_source', models.CharField(max_length=100)),
            ],
        ),
    ]
