# Generated by Django 4.1.1 on 2022-09-20 23:49

from django.db import migrations
import csv

def import_nonprofits(apps, schemaeditor):

    conv = lambda i : i or None
    RawNonprofit = apps.get_model('main', 'RawNonprofit')
    with open('main/data/nonprofits.csv') as csvfile:
        reader = csv.DictReader(csvfile)
        # 'EIN', 'NAME', 'ICO', 'STREET', 'CITY',
        # 'STATE', 'ZIP', 'GROUP', 'SUBSECTION',
        # 'AFFILIATION', 'CLASSIFICATION',
        # 'RULING', 'DEDUCTIBILITY', 'FOUNDATION',
        # 'ACTIVITY', 'ORGANIZATION', 'STATUS',
        # 'TAX_PERIOD', 'ASSET_CD', 'INCOME_CD',
        # 'FILING_REQ_CD', 'PF_FILING_REQ_CD',
        # 'ACCT_PD', 'ASSET_AMT', 'INCOME_AMT',
        # 'REVENUE_AMT', 'NTEE_CD', 'SORT_NAME',
        # 'Latitude', 'Longitude', 'Accuracy Score',
        # 'Accuracy Type', 'Number', 'Street',
        # 'City', 'State', 'County', 'Zip',
        # 'Country', 'Source']
        for row in reader:
            nonprofit = RawNonprofit(
                ein=row['EIN'],
                name=row['NAME'],
                ico=row['ICO'],
                street=row['STREET'],
                city=row['CITY'],
                state=row['STATE'],
                zip=row['ZIP'],
                group=row['GROUP'],
                subsection=row['SUBSECTION'],
                affiliation=row['AFFILIATION'],
                classification=row['CLASSIFICATION'],
                ruling=row['RULING'],
                deductibility=row['DEDUCTIBILITY'],
                foundation=row['FOUNDATION'],
                activity=row['ACTIVITY'],
                organization=row['ORGANIZATION'],
                status=row['STATUS'],
                tax_period=conv(row['TAX_PERIOD']),
                asset_cd=row['ASSET_CD'],
                income_cd=row['INCOME_CD'],
                filing_req_cd=row['FILING_REQ_CD'],
                pf_filing_req_cd=row['PF_FILING_REQ_CD'],
                acct_pd=row['ACCT_PD'],
                asset_amt=conv(row['ASSET_AMT']),
                income_amt=conv(row['INCOME_AMT']),
                revenue_amt=conv(row['REVENUE_AMT']),
                ntee_cd=row['NTEE_CD'],
                sort_name=row['SORT_NAME'],
                latitude=row['Latitude'],
                longitude=row['Longitude'],
                geo_accuracy_score=row['Accuracy Score'],
                geo_accuracy_type=row['Accuracy Type'],
                geo_number=row['Number'],
                geo_street=row['Street'],
                geo_city=row['City'],
                geo_state=row['State'],
                geo_county=row['County'],
                geo_zip=row['Zip'],
                geo_country=row['Country'],
                geo_source=row['Source'])
            nonprofit.save()

def remove_nonprofits(apps, schema_editor):
    RawNonprofit = apps.get_model('main', 'RawNonprofit')
    RawNonprofit.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_rawnonprofit'),
    ]

    operations = [
        migrations.RunPython(import_nonprofits, remove_nonprofits)
    ]
